package br.com.davidbuzatto.logosmoodle;

import br.com.davidbuzatto.jsge.core.engine.EngineFrame;
import br.com.davidbuzatto.jsge.core.utils.ColorUtils;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final String EXTENSAO = "lmo";
    
    private DrawWindow drawWindow;
    private JFileChooser jfc;
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        
        initComponents();
        
        jfc = new JFileChooser( "./" );
        jfc.setFileSelectionMode( JFileChooser.FILES_ONLY );
        jfc.setFileFilter( new FileNameExtensionFilter( "Logos Moodle", "lmo" ) );
        
        addWindowListener( new WindowAdapter() {
            @Override
            public void windowOpened( WindowEvent e ) {
                drawWindow = new DrawWindow();
                drawWindow.setLocation( getX() + getWidth(), getY() );
                drawWindow.reset();
                gerarEsquema( Color.BLACK );
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSiglaDisciplina = new javax.swing.JLabel();
        lblNomeDisciplina = new javax.swing.JLabel();
        lblNomeCurso = new javax.swing.JLabel();
        lblNomeProfessor = new javax.swing.JLabel();
        txtSiglaDisciplina = new javax.swing.JTextField();
        scrollNomeDisciplina = new javax.swing.JScrollPane();
        areaNomeDisciplina = new javax.swing.JTextArea();
        txtNomeCurso = new javax.swing.JTextField();
        txtNomeProfessor = new javax.swing.JTextField();
        checkMostrarCima = new javax.swing.JCheckBox();
        checkMostrarBaixo = new javax.swing.JCheckBox();
        checkMostrarBorda = new javax.swing.JCheckBox();
        painelCores = new javax.swing.JPanel();
        painelCoresFundo = new javax.swing.JPanel();
        lblCorFundo = new javax.swing.JLabel();
        painelCorFundo = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorBorda = new javax.swing.JLabel();
        painelCorBorda = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorCima = new javax.swing.JLabel();
        painelCorCima = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorBaixo = new javax.swing.JLabel();
        painelCorBaixo = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        painelCoresDisciplina = new javax.swing.JPanel();
        lblCorSigla = new javax.swing.JLabel();
        painelCorSigla = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorCimaSigla = new javax.swing.JLabel();
        painelCorCimaSigla = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorNomeDisciplina = new javax.swing.JLabel();
        painelCorNomeDisciplina = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        painelCoresCurso = new javax.swing.JPanel();
        lblCorNomeCurso = new javax.swing.JLabel();
        painelCorNomeCurso = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorBaixoNomeCurso = new javax.swing.JLabel();
        painelCorBaixoNomeCurso = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        painelCoresProfessor = new javax.swing.JPanel();
        lblCorNomeProfessor = new javax.swing.JLabel();
        painelCorNomeProfessor = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        lblCorBaixoNomeProfessor = new javax.swing.JLabel();
        painelCorBaixoNomeProfessor = new br.com.davidbuzatto.logosmoodle.PainelSelecaoCores();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();
        btnSalvarImagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logotipos para Cursos do Moodle");
        setResizable(false);

        lblSiglaDisciplina.setText("Sigla da Disciplina:");

        lblNomeDisciplina.setText("Nome da Disciplina:");

        lblNomeCurso.setText("Nome do Curso:");

        lblNomeProfessor.setText("Nome do Professor:");

        txtSiglaDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSiglaDisciplinaKeyReleased(evt);
            }
        });

        areaNomeDisciplina.setColumns(20);
        areaNomeDisciplina.setRows(5);
        areaNomeDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                areaNomeDisciplinaKeyReleased(evt);
            }
        });
        scrollNomeDisciplina.setViewportView(areaNomeDisciplina);

        txtNomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCursoKeyReleased(evt);
            }
        });

        txtNomeProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProfessorKeyReleased(evt);
            }
        });

        checkMostrarCima.setText("Mostrar Detalhe de Cima");
        checkMostrarCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostrarCimaActionPerformed(evt);
            }
        });

        checkMostrarBaixo.setText("Mostrar Detalhe de Baixo");
        checkMostrarBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostrarBaixoActionPerformed(evt);
            }
        });

        checkMostrarBorda.setText("Mostrar Borda");
        checkMostrarBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostrarBordaActionPerformed(evt);
            }
        });

        painelCores.setBorder(javax.swing.BorderFactory.createTitledBorder("Cores"));
        painelCores.setToolTipText("");

        lblCorFundo.setText("Fundo:");

        painelCorFundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorFundoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorFundoLayout = new javax.swing.GroupLayout(painelCorFundo);
        painelCorFundo.setLayout(painelCorFundoLayout);
        painelCorFundoLayout.setHorizontalGroup(
            painelCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorFundoLayout.setVerticalGroup(
            painelCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorBorda.setText("Borda:");

        painelCorBorda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorBordaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorBordaLayout = new javax.swing.GroupLayout(painelCorBorda);
        painelCorBorda.setLayout(painelCorBordaLayout);
        painelCorBordaLayout.setHorizontalGroup(
            painelCorBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorBordaLayout.setVerticalGroup(
            painelCorBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorCima.setText("Cima:");

        painelCorCima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorCimaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorCimaLayout = new javax.swing.GroupLayout(painelCorCima);
        painelCorCima.setLayout(painelCorCimaLayout);
        painelCorCimaLayout.setHorizontalGroup(
            painelCorCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorCimaLayout.setVerticalGroup(
            painelCorCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorBaixo.setText("Baixo:");

        painelCorBaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorBaixoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorBaixoLayout = new javax.swing.GroupLayout(painelCorBaixo);
        painelCorBaixo.setLayout(painelCorBaixoLayout);
        painelCorBaixoLayout.setHorizontalGroup(
            painelCorBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorBaixoLayout.setVerticalGroup(
            painelCorBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCoresFundoLayout = new javax.swing.GroupLayout(painelCoresFundo);
        painelCoresFundo.setLayout(painelCoresFundoLayout);
        painelCoresFundoLayout.setHorizontalGroup(
            painelCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCorFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorBorda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorCima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorBaixo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCoresFundoLayout.setVerticalGroup(
            painelCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCorCima)
                    .addComponent(lblCorFundo)
                    .addComponent(painelCorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorBorda)
                    .addComponent(painelCorCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorBaixo)
                    .addComponent(painelCorBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCorSigla.setText("Sigla:");

        painelCorSigla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorSiglaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorSiglaLayout = new javax.swing.GroupLayout(painelCorSigla);
        painelCorSigla.setLayout(painelCorSiglaLayout);
        painelCorSiglaLayout.setHorizontalGroup(
            painelCorSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorSiglaLayout.setVerticalGroup(
            painelCorSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorCimaSigla.setText("Sigla Cima:");

        painelCorCimaSigla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorCimaSiglaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorCimaSiglaLayout = new javax.swing.GroupLayout(painelCorCimaSigla);
        painelCorCimaSigla.setLayout(painelCorCimaSiglaLayout);
        painelCorCimaSiglaLayout.setHorizontalGroup(
            painelCorCimaSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorCimaSiglaLayout.setVerticalGroup(
            painelCorCimaSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorNomeDisciplina.setText("Nome da Disciplina:");

        painelCorNomeDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorNomeDisciplinaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorNomeDisciplinaLayout = new javax.swing.GroupLayout(painelCorNomeDisciplina);
        painelCorNomeDisciplina.setLayout(painelCorNomeDisciplinaLayout);
        painelCorNomeDisciplinaLayout.setHorizontalGroup(
            painelCorNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorNomeDisciplinaLayout.setVerticalGroup(
            painelCorNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCoresDisciplinaLayout = new javax.swing.GroupLayout(painelCoresDisciplina);
        painelCoresDisciplina.setLayout(painelCoresDisciplinaLayout);
        painelCoresDisciplinaLayout.setHorizontalGroup(
            painelCoresDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCorSigla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorCimaSigla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorCimaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorNomeDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCoresDisciplinaLayout.setVerticalGroup(
            painelCoresDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCoresDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCorSigla)
                    .addComponent(lblCorCimaSigla)
                    .addComponent(painelCorSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCorCimaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorNomeDisciplina)
                    .addComponent(painelCorNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCorNomeCurso.setText("Nome do Curso:");

        painelCorNomeCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorNomeCursoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorNomeCursoLayout = new javax.swing.GroupLayout(painelCorNomeCurso);
        painelCorNomeCurso.setLayout(painelCorNomeCursoLayout);
        painelCorNomeCursoLayout.setHorizontalGroup(
            painelCorNomeCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorNomeCursoLayout.setVerticalGroup(
            painelCorNomeCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorBaixoNomeCurso.setText("Baixo:");

        painelCorBaixoNomeCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorBaixoNomeCursoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorBaixoNomeCursoLayout = new javax.swing.GroupLayout(painelCorBaixoNomeCurso);
        painelCorBaixoNomeCurso.setLayout(painelCorBaixoNomeCursoLayout);
        painelCorBaixoNomeCursoLayout.setHorizontalGroup(
            painelCorBaixoNomeCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorBaixoNomeCursoLayout.setVerticalGroup(
            painelCorBaixoNomeCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCoresCursoLayout = new javax.swing.GroupLayout(painelCoresCurso);
        painelCoresCurso.setLayout(painelCoresCursoLayout);
        painelCoresCursoLayout.setHorizontalGroup(
            painelCoresCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCorNomeCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorBaixoNomeCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorBaixoNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCoresCursoLayout.setVerticalGroup(
            painelCoresCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCoresCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCorNomeCurso)
                    .addComponent(painelCorNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorBaixoNomeCurso)
                    .addComponent(painelCorBaixoNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCorNomeProfessor.setText("Nome do Professor");

        painelCorNomeProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorNomeProfessorMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorNomeProfessorLayout = new javax.swing.GroupLayout(painelCorNomeProfessor);
        painelCorNomeProfessor.setLayout(painelCorNomeProfessorLayout);
        painelCorNomeProfessorLayout.setHorizontalGroup(
            painelCorNomeProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorNomeProfessorLayout.setVerticalGroup(
            painelCorNomeProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lblCorBaixoNomeProfessor.setText("Baixo:");

        painelCorBaixoNomeProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelCorBaixoNomeProfessorMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelCorBaixoNomeProfessorLayout = new javax.swing.GroupLayout(painelCorBaixoNomeProfessor);
        painelCorBaixoNomeProfessor.setLayout(painelCorBaixoNomeProfessorLayout);
        painelCorBaixoNomeProfessorLayout.setHorizontalGroup(
            painelCorBaixoNomeProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorBaixoNomeProfessorLayout.setVerticalGroup(
            painelCorBaixoNomeProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCoresProfessorLayout = new javax.swing.GroupLayout(painelCoresProfessor);
        painelCoresProfessor.setLayout(painelCoresProfessorLayout);
        painelCoresProfessorLayout.setHorizontalGroup(
            painelCoresProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresProfessorLayout.createSequentialGroup()
                .addComponent(lblCorNomeProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorBaixoNomeProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorBaixoNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelCoresProfessorLayout.setVerticalGroup(
            painelCoresProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCoresProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCorNomeProfessor)
                    .addComponent(painelCorNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorBaixoNomeProfessor)
                    .addComponent(painelCorBaixoNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCoresLayout = new javax.swing.GroupLayout(painelCores);
        painelCores.setLayout(painelCoresLayout);
        painelCoresLayout.setHorizontalGroup(
            painelCoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCoresFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCoresDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCoresCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCoresProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCoresLayout.setVerticalGroup(
            painelCoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCoresFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCoresDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCoresCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCoresProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/logosmoodle/icones/page_white_add.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/logosmoodle/icones/folder.png"))); // NOI18N
        btnAbrir.setToolTipText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/logosmoodle/icones/disk.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/logosmoodle/icones/palette.png"))); // NOI18N
        btnGerar.setToolTipText("Gerar Esquema");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnSalvarImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/logosmoodle/icones/picture_save.png"))); // NOI18N
        btnSalvarImagem.setToolTipText("Salvar como Imagem");
        btnSalvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSiglaDisciplina, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomeDisciplina, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomeCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomeProfessor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollNomeDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtSiglaDisciplina, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeCurso)
                            .addComponent(txtNomeProfessor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkMostrarBaixo)
                                    .addComponent(checkMostrarCima)
                                    .addComponent(checkMostrarBorda))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(painelCores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarImagem)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSiglaDisciplina)
                    .addComponent(txtSiglaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeDisciplina)
                    .addComponent(scrollNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCurso)
                    .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkMostrarCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkMostrarBaixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkMostrarBorda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvarImagem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnSalvar)
                    .addComponent(btnAbrir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSiglaDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiglaDisciplinaKeyReleased
        drawWindow.setSiglaDisciplina( txtSiglaDisciplina.getText() );
    }//GEN-LAST:event_txtSiglaDisciplinaKeyReleased

    private void areaNomeDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaNomeDisciplinaKeyReleased
        drawWindow.setNomeDisciplina( areaNomeDisciplina.getText() );
    }//GEN-LAST:event_areaNomeDisciplinaKeyReleased

    private void txtNomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCursoKeyReleased
        drawWindow.setNomeCurso( txtNomeCurso.getText() );
    }//GEN-LAST:event_txtNomeCursoKeyReleased

    private void txtNomeProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProfessorKeyReleased
        drawWindow.setNomeProfessor( txtNomeProfessor.getText() );
    }//GEN-LAST:event_txtNomeProfessorKeyReleased

    private void checkMostrarCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarCimaActionPerformed
        drawWindow.setMostrarCima( checkMostrarCima.isSelected() );
    }//GEN-LAST:event_checkMostrarCimaActionPerformed

    private void checkMostrarBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarBaixoActionPerformed
        drawWindow.setMostrarBaixo( checkMostrarBaixo.isSelected() );
    }//GEN-LAST:event_checkMostrarBaixoActionPerformed

    private void checkMostrarBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarBordaActionPerformed
        drawWindow.setMostrarBorda( checkMostrarBorda.isSelected() );
    }//GEN-LAST:event_checkMostrarBordaActionPerformed

    private void painelCorFundoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorFundoMouseReleased
        abrirSelecaoCor( painelCorFundo, "Cor do Fundo" );
        drawWindow.setCorFundo( painelCorFundo.getCor() );
    }//GEN-LAST:event_painelCorFundoMouseReleased

    private void painelCorBordaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorBordaMouseReleased
        abrirSelecaoCor( painelCorBorda, "Cor da Borda" );
        drawWindow.setCorBorda( painelCorBorda.getCor() );
    }//GEN-LAST:event_painelCorBordaMouseReleased

    private void painelCorCimaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorCimaMouseReleased
        abrirSelecaoCor( painelCorCima, "Cor do Detalhe de Cima" );
        drawWindow.setCorCima( painelCorCima.getCor() );
    }//GEN-LAST:event_painelCorCimaMouseReleased

    private void painelCorBaixoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorBaixoMouseReleased
        abrirSelecaoCor( painelCorBaixo, "Cor do Detalhe de Baixo" );
        drawWindow.setCorBaixo( painelCorBaixo.getCor() );
    }//GEN-LAST:event_painelCorBaixoMouseReleased

    private void painelCorSiglaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorSiglaMouseReleased
        abrirSelecaoCor( painelCorSigla, "Cor da Sigla da Disciplina" );
        drawWindow.setCorSigla( painelCorSigla.getCor() );
    }//GEN-LAST:event_painelCorSiglaMouseReleased

    private void painelCorCimaSiglaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorCimaSiglaMouseReleased
        abrirSelecaoCor( painelCorCimaSigla, "Cor da Sigla da Disciplina no Detalhe de Cima" );
        drawWindow.setCorCimaSigla( painelCorCimaSigla.getCor() );
    }//GEN-LAST:event_painelCorCimaSiglaMouseReleased

    private void painelCorNomeDisciplinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorNomeDisciplinaMouseReleased
        abrirSelecaoCor( painelCorNomeDisciplina, "Cor do Nome da Disciplina" );
        drawWindow.setCorNomeDisciplina( painelCorNomeDisciplina.getCor() );
    }//GEN-LAST:event_painelCorNomeDisciplinaMouseReleased

    private void painelCorNomeCursoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorNomeCursoMouseReleased
        abrirSelecaoCor( painelCorNomeCurso, "Cor do Nome do Curso" );
        drawWindow.setCorNomeCurso( painelCorNomeCurso.getCor() );
    }//GEN-LAST:event_painelCorNomeCursoMouseReleased

    private void painelCorBaixoNomeCursoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorBaixoNomeCursoMouseReleased
        abrirSelecaoCor( painelCorBaixoNomeCurso, "Cor do Nome do Curso do Detalhe de Baixo" );
        drawWindow.setCorBaixoNomeCurso( painelCorBaixoNomeCurso.getCor() );
    }//GEN-LAST:event_painelCorBaixoNomeCursoMouseReleased

    private void painelCorNomeProfessorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorNomeProfessorMouseReleased
        abrirSelecaoCor( painelCorNomeProfessor, "Cor do Nome do Professor" );
        drawWindow.setCorNomeProfessor( painelCorNomeProfessor.getCor() );
    }//GEN-LAST:event_painelCorNomeProfessorMouseReleased

    private void painelCorBaixoNomeProfessorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorBaixoNomeProfessorMouseReleased
        abrirSelecaoCor( painelCorBaixoNomeProfessor, "Cor do Nome do Professor do Detalhe de Baixo" );
        drawWindow.setCorBaixoNomeProfessor( painelCorBaixoNomeProfessor.getCor() );
    }//GEN-LAST:event_painelCorBaixoNomeProfessorMouseReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        if ( JOptionPane.showConfirmDialog( 
                this, 
                "Deseja criar um novo logotipo?", 
                "Confirmação", 
                JOptionPane.YES_NO_OPTION
             ) == JOptionPane.YES_OPTION ) {
            
            drawWindow.reset();
            gerarEsquema( Color.BLACK );
            
            // SBVAPRC
            //gerarEsquema( new Color( 23, 147, 195 ) );
            
            // SBVESDD
            //gerarEsquema( new Color( 46, 130, 163 ) );
            
            // SBVCONC
            //gerarEsquema( new Color( 66, 135, 38 ) );
            
            // SBVORIN
            //gerarEsquema( new Color( 39, 111, 139 ) );
            
            
        }
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        Color base = JColorChooser.showDialog( this, "Escolha uma cor base", drawWindow.getCorSigla() );
        gerarEsquema( base );
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnSalvarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarImagemActionPerformed
        
        JFileChooser jfc = new JFileChooser( "./" );
        jfc.setDialogTitle( "Salvar Imagem Como" );
        jfc.setMultiSelectionEnabled( false );
        jfc.setDialogType( JFileChooser.SAVE_DIALOG );
        jfc.showDialog( this, null );
        
        jfc.addComponentListener( new ComponentAdapter() {
            @Override
            public void componentHidden( ComponentEvent e ) {
                new Thread( () -> {
                    try {
                        File f = jfc.getSelectedFile();
                        if ( f != null ) {
                            if ( !f.getName().toLowerCase().endsWith( ".png" ) ) {
                                f = new File( f.getAbsolutePath() + ".png" );
                            }
                            boolean ok;
                            if ( f.exists() ) {
                                if ( JOptionPane.showConfirmDialog( 
                                        null, 
                                        "O arquivo já existe! Deseja o sobrescrever?", 
                                        "Confirmação", 
                                        JOptionPane.YES_NO_OPTION
                                    ) == JOptionPane.YES_OPTION ) {
                                    ok = true;
                                } else {
                                    ok = false;
                                }
                            } else {
                                ok = true;
                            }
                            if ( ok ) {
                                Thread.sleep( 1000 );
                                drawWindow.salvarImagem( f );
                            }
                        }
                    } catch ( InterruptedException exc ) {
                    }
                }).start();
            }
        });
        
        jfc.setVisible( false );
        
    }//GEN-LAST:event_btnSalvarImagemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        DadosLogo d = new DadosLogo(
            txtSiglaDisciplina.getText(), 
            areaNomeDisciplina.getText(), 
            txtNomeCurso.getText(), 
            txtNomeProfessor.getText(), 
            checkMostrarCima.isSelected(), 
            checkMostrarBaixo.isSelected(), 
            checkMostrarBorda.isSelected(), 
            painelCorFundo.getCor(), 
            painelCorBorda.getCor(), 
            painelCorCima.getCor(), 
            painelCorBaixo.getCor(), 
            painelCorSigla.getCor(), 
            painelCorCimaSigla.getCor(), 
            painelCorNomeDisciplina.getCor(), 
            painelCorNomeCurso.getCor(), 
            painelCorBaixoNomeCurso.getCor(), 
            painelCorNomeProfessor.getCor(), 
            painelCorBaixoNomeProfessor.getCor()
        );
        
        jfc.setDialogTitle( "Salvar" );
        jfc.showSaveDialog( this );
        
        File f = jfc.getSelectedFile();
        
        if ( f != null ) {
            
            if ( !f.getName().endsWith( EXTENSAO ) ) {
                f = new File( f.getAbsolutePath() + "." + EXTENSAO );
            }
            
            boolean ok = true;
            
            if ( f.exists() ) {
                if ( JOptionPane.showConfirmDialog( 
                        null, 
                        "O arquivo já existe! Deseja o sobrescrever?", 
                        "Confirmação", 
                        JOptionPane.YES_NO_OPTION
                    ) == JOptionPane.YES_OPTION ) {
                    ok = true;
                } else {
                    ok = false;
                }
            }
            
            if ( ok ) {
                try ( FileOutputStream fos = new FileOutputStream( f );
                      ObjectOutputStream oos = new ObjectOutputStream( fos ); ) {

                    oos.writeObject( d );

                } catch ( IOException exc ) {
                    exc.printStackTrace();
                }
            }
            
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        
        jfc.setDialogTitle( "Abrir" );
        jfc.showOpenDialog( this );
        
        File f = jfc.getSelectedFile();
        
        if ( f != null ) {
            
            try ( FileInputStream fis = new FileInputStream( f );
                  ObjectInputStream ois = new ObjectInputStream( fis ); ) {

                DadosLogo d = (DadosLogo) ois.readObject();

                txtSiglaDisciplina.setText( d.siglaDisciplina() ); 
                areaNomeDisciplina.setText( d.nomeDisciplina() ); 
                txtNomeCurso.setText( d.nomeCurso() ); 
                txtNomeProfessor.setText( d.nomeProfessor() ); 
                checkMostrarCima.setSelected( d.mostrarDetalheCima() ); 
                checkMostrarBaixo.setSelected( d.mostrarDetalheBaixo() ); 
                checkMostrarBorda.setSelected( d.mostrarBorda() );
                painelCorFundo.setCor( d.corFundo() ); 
                painelCorBorda.setCor( d.corBorda() ); 
                painelCorCima.setCor( d.corCima() ); 
                painelCorBaixo.setCor( d.corBaixo() ); 
                painelCorSigla.setCor( d.corSigla() ); 
                painelCorCimaSigla.setCor( d.corSiglaCima() ); 
                painelCorNomeDisciplina.setCor( d.corNomeDisciplina() ); 
                painelCorNomeCurso.setCor( d.corNomeCurso() ); 
                painelCorBaixoNomeCurso.setCor( d.corNomeCursoBaixo() ); 
                painelCorNomeProfessor.setCor( d.corNomeProfessor() ); 
                painelCorBaixoNomeProfessor.setCor( d.corNomeProfessorBaixo() );
                
                drawWindow.setSiglaDisciplina( d.siglaDisciplina() ); 
                drawWindow.setNomeDisciplina( d.nomeDisciplina() ); 
                drawWindow.setNomeCurso( d.nomeCurso() ); 
                drawWindow.setNomeProfessor( d.nomeProfessor() ); 
                drawWindow.setMostrarCima( d.mostrarDetalheCima() ); 
                drawWindow.setMostrarBaixo( d.mostrarDetalheBaixo() ); 
                drawWindow.setMostrarBorda( d.mostrarBorda() );
                drawWindow.setCorFundo( d.corFundo() ); 
                drawWindow.setCorBorda( d.corBorda() ); 
                drawWindow.setCorCima( d.corCima() ); 
                drawWindow.setCorBaixo( d.corBaixo() ); 
                drawWindow.setCorSigla( d.corSigla() ); 
                drawWindow.setCorCimaSigla( d.corSiglaCima() ); 
                drawWindow.setCorNomeDisciplina( d.corNomeDisciplina() ); 
                drawWindow.setCorNomeCurso( d.corNomeCurso() ); 
                drawWindow.setCorBaixoNomeCurso( d.corNomeCursoBaixo() ); 
                drawWindow.setCorNomeProfessor( d.corNomeProfessor() ); 
                drawWindow.setCorBaixoNomeProfessor( d.corNomeProfessorBaixo() );

            } catch ( IOException | ClassNotFoundException exc ) {
                exc.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void abrirSelecaoCor( PainelSelecaoCores painel, String titulo ) {
        
        Color c = JColorChooser.showDialog( this, titulo, painel.getCor() );
        if ( c != null ) {
            painel.setCor( c );
            painel.repaint();
        }
        
    }
    
    private void atualizar() {
        
        txtSiglaDisciplina.setText( drawWindow.getSiglaDisciplina() );
        areaNomeDisciplina.setText( drawWindow.getNomeDisciplina() );
        txtNomeCurso.setText( drawWindow.getNomeCurso() );
        txtNomeProfessor.setText( drawWindow.getNomeProfessor() );
        checkMostrarCima.setSelected( drawWindow.isMostrarCima() );
        checkMostrarBaixo.setSelected( drawWindow.isMostrarBaixo() );
        checkMostrarBorda.setSelected( drawWindow.isMostrarBorda() );
        
        painelCorFundo.setCor( drawWindow.getCorFundo() );
        painelCorBorda.setCor( drawWindow.getCorBorda() );
        painelCorCima.setCor( drawWindow.getCorCima() );
        painelCorBaixo.setCor( drawWindow.getCorBaixo() );
        painelCorSigla.setCor( drawWindow.getCorSigla() );
        painelCorCimaSigla.setCor( drawWindow.getCorCimaSigla() );
        painelCorNomeDisciplina.setCor( drawWindow.getCorNomeDisciplina());
        painelCorNomeCurso.setCor( drawWindow.getCorNomeCurso());
        painelCorBaixoNomeCurso.setCor( drawWindow.getCorBaixoNomeCurso());
        painelCorNomeProfessor.setCor( drawWindow.getCorNomeProfessor());
        painelCorBaixoNomeProfessor.setCor( drawWindow.getCorBaixoNomeProfessor() );
        
    }
    
    private void gerarEsquema( Color base ) {
        
        if ( base != null ) {
            
            Color cima = ColorUtils.colorBrightness( base, -.8 );
            Color baixo = ColorUtils.colorBrightness( base, .1 );
            
            drawWindow.setCorFundo( EngineFrame.RAYWHITE );
            drawWindow.setCorBorda( Color.BLACK );
            drawWindow.setCorCima( cima );
            drawWindow.setCorBaixo( baixo );
            drawWindow.setCorSigla( base );
            drawWindow.setCorCimaSigla( Color.WHITE );
            drawWindow.setCorNomeDisciplina( new Color( 38, 38, 38 ) );
            drawWindow.setCorNomeCurso( Color.BLACK );
            drawWindow.setCorBaixoNomeCurso( EngineFrame.RAYWHITE );
            drawWindow.setCorNomeProfessor( Color.BLACK );
            drawWindow.setCorBaixoNomeProfessor( EngineFrame.RAYWHITE );
            
            atualizar();
            
        }
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                FlatDarkLaf.setup();
                new JanelaPrincipal().setVisible( true );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaNomeDisciplina;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarImagem;
    private javax.swing.JCheckBox checkMostrarBaixo;
    private javax.swing.JCheckBox checkMostrarBorda;
    private javax.swing.JCheckBox checkMostrarCima;
    private javax.swing.JLabel lblCorBaixo;
    private javax.swing.JLabel lblCorBaixoNomeCurso;
    private javax.swing.JLabel lblCorBaixoNomeProfessor;
    private javax.swing.JLabel lblCorBorda;
    private javax.swing.JLabel lblCorCima;
    private javax.swing.JLabel lblCorCimaSigla;
    private javax.swing.JLabel lblCorFundo;
    private javax.swing.JLabel lblCorNomeCurso;
    private javax.swing.JLabel lblCorNomeDisciplina;
    private javax.swing.JLabel lblCorNomeProfessor;
    private javax.swing.JLabel lblCorSigla;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblNomeDisciplina;
    private javax.swing.JLabel lblNomeProfessor;
    private javax.swing.JLabel lblSiglaDisciplina;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorBaixo;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorBaixoNomeCurso;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorBaixoNomeProfessor;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorBorda;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorCima;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorCimaSigla;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorFundo;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorNomeCurso;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorNomeDisciplina;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorNomeProfessor;
    private br.com.davidbuzatto.logosmoodle.PainelSelecaoCores painelCorSigla;
    private javax.swing.JPanel painelCores;
    private javax.swing.JPanel painelCoresCurso;
    private javax.swing.JPanel painelCoresDisciplina;
    private javax.swing.JPanel painelCoresFundo;
    private javax.swing.JPanel painelCoresProfessor;
    private javax.swing.JScrollPane scrollNomeDisciplina;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtNomeProfessor;
    private javax.swing.JTextField txtSiglaDisciplina;
    // End of variables declaration//GEN-END:variables
}
